### ISSUE TITLE
There should be a setting to disable it

### ISSUE THREAD

**Issue by stevevance** [zidizei/debug-php#1]
The only way I can see disabling it is by making a local variable with a boolean value and then using the ternary operator to quickly check to see if we should engage the debugger or not. 

Example of how I'm doing it:

```
$debug = true;
($debug ? \Debug\profile("parser") : null );
```

It would be cool to use \Debug\on to turn it on and \Debug\off to turn it off.

**Comment by zidizei** [comment]
Thanks for the feedback. It's been a while since I worked on this, but I like your suggestion and it should be easy enough to implement.
